# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.1
loader_version=0.18.4
# Mod Properties
mod_version=1.0-release-1.21.1fabric
maven_group=org.stargest
archives_base_name=nst-revolvers-recoiled
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.116.9+1.21.1
geckolib_version = 4.8.4
